"""empty message

Revision ID: aa405cef055e
Revises: fa5875562e92
Create Date: 2019-12-26 00:26:11.286261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa405cef055e'
down_revision = 'fa5875562e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_table') as batch_op:
        batch_op.drop_column('added_string_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_table', sa.Column('added_string_field', sa.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
