"""empty message

Revision ID: ae6e5eeb3335
Revises: 
Create Date: 2019-12-26 00:21:59.871823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6e5eeb3335'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_field', sa.String(length=80), nullable=True),
    sa.Column('text_field', sa.Text(), nullable=True),
    sa.Column('date_field', sa.DateTime(), nullable=True),
    sa.Column('float_field', sa.Float(), nullable=True),
    sa.Column('boolean_field', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    # ### end Alembic commands ###
